version: "3.8"
services:
  myapp:
    image: myapp
    container_name: full_stack_app
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - mydb
  mydb:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - ./data:/data/db

networks:
  my-network:
